title = "Hello World"
baseURL = "https://barret-pierre.github.io/Hugo/"
languageCode = "en-us"
theme = 'ananke'

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Hello World"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "Hello World"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color_class = ""
  author = ""
  favicon = ""
  site_logo = ""
  commentoEnable = true
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  custom_css = ["theme.css"]
  background_color_class = "bg-green"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
