title = "BLOG.IO"
baseURL='https://barret-pierre.github.io/Hugo/'
languageCode = "en-us"
theme = 'ananke'
summaryLength = 40

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "BLOG.IO"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "BLOG.IO"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color_class = ""
  author = ""
  favicon = ""
  site_logo = ""
  commentoEnable = false
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  custom_css = ["theme.css", "footer.css", "sumary-with-image.css"]
  background_color_class = "bg-light-gray"
  recent_posts_number = 4
  summaryLength = 30

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/Barret-Pierre?tab=repositories"
[[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/pierre-alexandre-barret-1a99171b0/"
[[params.ananke_socials]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/17179968/pierre-alexandre-barret"
